spring.application.name=notifyme-backend

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.acknowledge-mode=auto

# NotifyMe messaging setup
notifyme.exchange=jutjubic.upload
notifyme.queue=notifyme.upload.events.v2
notifyme.routing-key=upload.created

spring.rabbitmq.virtual-host=/

notifyme.dlx=notifyme.upload.dlx
notifyme.dlq=notifyme.upload.events.dlq
notifyme.dlq-routing-key=upload.created.dlq


spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false
#privremeno
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG

server.port=8082

spring.jackson.serialization.write-dates-as-timestamps=false
